services:
  - type: web
    name: yolo-black-bear-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
